# Site Settings
title:               "Rachith Prakash"
tagline:             "Masters Candidate in Robotics at the University of Maryland, College Park"
description:         
baseurl:             # /
url: 			           
github:
  repo:              "https://github.com/rachithp/rachithp.github.io"
author:
  name:              "Rachith Prakash"
  email:             "rprakas2@umd.edu"
  twitter:           "314159265358980"
  instagram:         
  github:            "rachithp"
  facebook:          
  linkedin:          "rachithprakash"
  scholar:           
paginate:            15
paginate_path:       "/blog/page:num/"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           pretty
plugins:             [jekyll-paginate]

# Collections
collections:
  - projects
